sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: k2brldjAtHJ5U0yFi2p8aPip8QYTt8
    bucket-name: bigevent1234567890
    access-key-id: LTAI5tHmTgQJkqBv5sKv7jax
